CREATE TABLE money (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    balance NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    budget NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    ratio FLOAT NOT NULL DEFAULT 0.0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE
);
