CREATE TABLE money (
    id SERIAL PRIMARY KEY,
    balance NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    budget NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    ratio FLOAT NOT NULL DEFAULT 0.0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id SERIAL REFERENCES users(id) ON DELETE CASCADE,
    user_email VARCHAR(100) NOT NULL REFERENCES users(email) ON DELETE CASCADE
);
